version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/joshdk/tfbundle
    steps:
      - checkout
      - run: go get -u github.com/jteeuwen/go-bindata/...
      - run: ./godelw version
      - run: ./godelw verify --apply=false
