products:
  tfbundle:
    build:
      output-dir: ./build/bin
      main-pkg: .
      version-var: github.com/joshdk/tfbundle/cmd.version
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
    dist:
      output-dir: ./build/dist
      dist-type:
        type: os-arch-bin
